name: Test Java Problem Matcher

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Register Java problem matcher
      #   run: echo "::add-matcher::.github/java-problem-matcher.json"

      - name: Simulate Java compiler output
        run: |
          echo "/home/runner/work/user/repo/src/Test.java:203: warning: [dep-ann] deprecated item is not annotated with @Deprecated"
          echo "/home/runner/work/user/repo/src/Test.java:563: error: cannot find symbol"
