name: 689 PR Test

on:
  workflow_dispatch:

jobs:
  PR-689-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: priyagupta108/setup-java@fix-windows-archive-extraction
        with:
            distribution: microsoft
            java-version: 17
