name: "739 Issue"

on: 
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - run: ". .github/workflows/tools.sh"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "corretto"
        java-version: "$JAVA_VERSION"
