name: "739 Issue"

on: 
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - name: Set up Java version
      run: |
        ". .github/workflows/tools.sh"  # Load the tools.sh script
        " echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV" 
    - uses: "actions/setup-java@v4"
      with:
        distribution: "corretto"
        java-version: "${{ env.JAVA_VERSION }}"
