name: "739 Issue"

on: 
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - name: Set up Java version
      run: |
        . .github/workflows/tools.sh  # Load the tools.sh script
      # echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
    - uses: "actions/setup-java@v4"
      with:
        distribution: "corretto"
        java-version: $JAVA_VERSION


    # - name: Set up Java version
    #   run: |
    #     source .github/workflows/tools.sh  # Load the tools.sh script
    #     echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV  # Export JAVA_VERSION to the environment
