name: 908 error

on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    name: "Build"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21.0.8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
