
name: GraalVM Cache Check

on:
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        java-version: ['17','21','22']
        os: ['ubuntu-latest','windows-latest','macos-latest']
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-java@fniephaus/graalvm
        with:
           distribution: 'graalvm'
           java-version: ${{matrix.java-version}}
           cache: 'maven'
           cache-dependency-path: 'pom.xml'
         
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
