name: SBT Check against Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [microsoft, oracle, temurin, corretto, liberica, dragonwell, sapmachine]
        version: [8, 11, 17 ,21, 22]
        exclude:
          - distribution: microsoft
            version: 8
          - distribution: microsoft
            version: 22  
          - distribution: oracle
            version: 8
          - distribution: oracle
            version: 11
          - distribution: graalvm
            version: 8
          - distribution: graalvm
            version: 11
          - distribution: sapmachine
            version: 8
          - distribution: temurin
            version: 8
          - distribution: temurin
            version: 22
          - distribution: dragonwell
            version: 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: ${{ matrix.distribution }}
            java-version: ${{ matrix.version }}
            cache: 'sbt'    
      - name: Install SBT
        run: |
          echo "Installing SBT"
          curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
          sudo mv sbt-rpm.repo /etc/yum.repos.d/
          sudo yum install sbt
      - name: Build with SBT
        run: sbt package
