name: Check Latest against Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest, macos-13, macos-latest]
        version: [11, 17 ,21]
        exclude:
          - distribution: microsoft
            version: 8
          - distribution: microsoft
            version: 22  
          - distribution: oracle
            version: 8
          - distribution: oracle
            version: 11
          - distribution: graalvm
            version: 8
          - distribution: graalvm
            version: 11
          - distribution: sapmachine
            version: 8
          - distribution: temurin
            version: 8
          - distribution: temurin
            version: 22
          - distribution: dragonwell
            version: 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gmitch215/setup-java@main
        with:
            distribution: jetbrains
            java-version: ${{ matrix.version }}
            check-latest: true
