name: Playground
run-name: Playground
on: 
  workflow_dispatch:
jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17.0.10'
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/
            # ls -la $RUNNER_TOOL_CACHE/Java_Microsoft_jdk/

      - name: Setup Java Again
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17.0.10'
