name: Playground
run-name: Playground
on: 
  workflow_dispatch:
jobs:
  playground:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # matrix:
      #   distribution: [microsoft, zulu ,temurin, corretto, adopt, liberica, sapmachine, dragonwell, semuru]

    steps:
      - name: Setup Java 
        uses: mahabaleshwars/setup-java@fix/corretto
        with:
          # distribution: ${{ matrix.distribution }}
          distribution: corretto
          java-version: '8.362.10'
      
      # - name: List Java JDK Directories
      #   run: |
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Corretto_jdk/" ]; then
      #       echo "Contents of Java_Corretto_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Microsoft_jdk/" ]; then
      #       echo "Contents of Java_Microsoft_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Microsoft_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Zulu_jdk/" ]; then
      #       echo "Contents of Java_Zulu_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Zulu_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Temurin_jdk/" ]; then
      #       echo "Contents of Java_Temurin_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Temurin_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Adopt_jdk/" ]; then
      #       echo "Contents of Java_Adopt_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Adopt_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Liberica_jdk/" ]; then
      #       echo "Contents of Java_Liberica_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Liberica_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_SapMachine_jdk/" ]; then
      #       echo "Contents of Java_SapMachine_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_SapMachine_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Dragonwell_jdk/" ]; then
      #       echo "Contents of Java_Dragonwell_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Dragonwell_jdk/
      #     fi
      #     if [ -d "$RUNNER_TOOL_CACHE/Java_Semuru_jdk/" ]; then
      #       echo "Contents of Java_Semuru_jdk:"
      #       ls -la $RUNNER_TOOL_CACHE/Java_Semuru_jdk/
      #     fi

      - name: Print directory contents
        run: ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/
        env:
          RUNNER_TOOL_CACHE: ${{ runner.tool_cache }}

      - name: Setup Java Again
        uses: mahabaleshwars/setup-java@fix/corretto
        with:
          distribution: corretto
          # distribution:  ${{ matrix.distribution }}
          java-version: '8.362.10'
