name: Playground
run-name: Playground
on: 
  workflow_dispatch:
jobs:
  playground:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution: [microsoft, zulu ,temurin, corretto, adopt, liberica, sapmachine, dragonwell, semuru]

    steps:
      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '8'
      
      # - name: Check Runner ToolCache
      #   run: |
      #     ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/
      #       # ls -la $RUNNER_TOOL_CACHE/Java_Microsoft_jdk/
      - name: Print Tool Cache Path
        run: echo $RUNNER_TOOL_CACHE

      - name: Setup Java Again
        uses: actions/setup-java@v4
        with:
          distribution:  ${{ matrix.distribution }}
          java-version: '8'
