
name: JetBrains Get Latest Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [21.0.5-b631.16, 17.0.5-b653.6, 17.0.5-b469.67]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gmitch215/setup-java@main
        with:
            distribution: jetbrains
            java-version: ${{ matrix.version }}
            check-latest: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
