name: JetBrains Get Latest Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [21.0.4, 21.0.2,17.0.12, 17.0.11, 17.0.10, 17.0.6, 11_0_16, 11_0_14,11_0_13, 11.0.11+9,11_0_10]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gmitch215/setup-java@main
        with:
            distribution: jetbrains
            java-version: ${{ matrix.version }}
            check-latest: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
