name: JetBrains Get Latest Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        # version: [21.0.4, 21.0.2,17.0.12, 17.0.11, 17.0.10, 17.0.6, 11.0.16, 11.0.14,11.0.13, 11.0.11+9,11.0.10]
        version: [11, 17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: mahabaleshwars/setup-java-main@main
        with:
            distribution: jetbrains
            java-version: ${{ matrix.version }}
            check-latest: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
