name: JetBrains Get Latest Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest, macos-latest, macos-13]
        version: [11, 17, 21]
        package: [jdk, jre, jdk+jcef, jre+jcef, jdk+ft, jre+ft]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gmitch215/setup-java@main
        with:
            distribution: jetbrains
            java-version: ${{ matrix.version }}
            java-package: ${{ matrix.package }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
