name: JetBrains Get Latest Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13]
        version: [11, 17 ,21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gmitch215/setup-java@main
        with:
            distribution: jetbrains
            java-version: 11
            # ${{ matrix.version }}
            check-latest: true
