name: JAVA_HOME Path Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: mahabaleshwars/setup-java@fix/architecture-variable
        with: 
          distribution: zulu
          java-version: 17
          # architecture: aarch64
