name: Java 25 Build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '25'
      
      - name: Verify Java version
        run: java -version
