name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JAva
        uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
         
