name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          version: [17.0.12,21,22,23,24]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: graalvm
          java-version: ${{ matrix.version }}
         
