name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [temurin, adopt, liberica, adopt-openj9, corretto, zulu, microsoft, semeru, oracle, dragonwell, sapmachine, jetbrains, graalvm]
        version: [21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@dependabot/npm_and_yarn/undici-5.29.0
        with:
          distribution: ${{ matrix.os }}
          java-version: ${{ matrix.version }}
