name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JAva
        uses: actions/setup-java@DependabotSetup
        with:
          java-version: 17
          distribution: microsoft
