name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: graalvm
          java-version: 21
         
