name: New PR Test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: aparnajyothi-y/setup-java@tool-versions-regex-fix
        with:
          #java-version-file: .tool-versions
          java-version: 19.0.0-beta+36.0.202208190932
          distribution: adopt
         
