name: SBT Check against Ubuntu Test New

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [microsoft, oracle, temurin, corretto, liberica, dragonwell, sapmachine]
        version: [8, 11, 17 ,21, 22]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: microsoft
            java-version: 17
            cache: 'sbt'    
      - name: Update package list
        run: sudo apt-get update
      
      - name: Add the SBT repository
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add -
      
      - name: Install SBT
        run: sudo apt-get install -y sbt

      - name: Build with SBT
        run: sbt package
