name: JetBrains SBT Cache Check with Dependencies 

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [11, 17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: gmitch215/setup-java@main
        with:
          distribution: jetbrains
          java-version: ${{ matrix.version }}
          cache: maven
          cache-dependency-path: build.sbt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SBT on macOS
        if: runner.os == 'macOS'
        run: |
          brew install sbt

      - name: Build with SBT
        run: sbt package

      - name: Verify Java version
        run: java -version
         
