name: Tool Version Compatibility Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubunutu-latest
    strategy:
      matrix:
        distribution: [microsoft, zulu, oracle, temurin, semuru, liberica, corretto, drangonwell,]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: matrix.distribution
          java-version-file: .tool-versions
