name: Tool-version new regex

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java usng tool-versions
        uses: aparnajyothi-y/setup-java@toolversions-regex-update
        with:
          distribution: liberica
          java-version-file: .tool-versions
